services:
  cvmfs-repo-consumers:                                                                                 
    image: cvmfs-repo-consumers:latest
    container_name: cvmfs-repo-consumers
    hostname: cvmfs-repo-consumers
    restart: unless-stopped
    network_mode: cvmfs-publisher-docker-network
    volumes:
      - ./certs:/app/certs
      - ./src/parameters.json:/app/parameters.json
      - /data/cvmfs:/data/cvmfs
      - /var/log/publisher:/var/log/publisher

  cvmfs-repo-sync:
    image: sync-publisher:latest
    container_name: cvmfs-repo-sync
    hostname: cvmfs-repo-sync
    privileged: true
    user: root
    restart: unless-stopped
    command: python /app/cvmfs_repo_sync.py 
    network_mode: cvmfs-publisher-docker-network
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
    volumes:
      - ./certs:/app/certs
      - ./src/parameters.json:/app/parameters.json
      - ./src/cvmfs_repo_sync.py:/app/cvmfs_repo_sync.py
      - /data/cvmfs:/data/cvmfs
      - /var/spool/cvmfs:/var/spool/cvmfs
      - /var/log/publisher:/var/log/publisher

  publisher-consumer: 
    image: sync-publisher:latest        
    container_name: publisher-consumer
    hostname: publisher-consumer
    privileged: true
    user: root
    restart: unless-stopped
    command: python /app/publisher_consumer.py
    network_mode: cvmfs-publisher-docker-network
    devices:
      - /dev/fuse
    cap_add:
      - SYS_ADMIN
    security_opt:
      - apparmor=unconfined
    volumes:
      - ./certs:/app/certs
      - ./src/parameters.json:/app/parameters.json
      - ./src/publisher_consumer.py:/app/publisher_consumer.py
      - /var/log/publisher:/var/log/publisher
      - /var/spool/cvmfs:/var/spool/cvmfs

